# Bash insecure code sample
eval $input  # Vulnerability 1
eval $input  # Vulnerability 2
eval $input  # Vulnerability 3
eval $input  # Vulnerability 4
eval $input  # Vulnerability 5
eval $input  # Vulnerability 6
eval $input  # Vulnerability 7
eval $input  # Vulnerability 8
eval $input  # Vulnerability 9
eval $input  # Vulnerability 10
eval $input  # Vulnerability 11
eval $input  # Vulnerability 12
eval $input  # Vulnerability 13
eval $input  # Vulnerability 14
eval $input  # Vulnerability 15
eval $input  # Vulnerability 16
eval $input  # Vulnerability 17
eval $input  # Vulnerability 18
eval $input  # Vulnerability 19
eval $input  # Vulnerability 20