// C insecure code sample
gets(buffer);  // Vulnerability 1
gets(buffer);  // Vulnerability 2
gets(buffer);  // Vulnerability 3
gets(buffer);  // Vulnerability 4
gets(buffer);  // Vulnerability 5
gets(buffer);  // Vulnerability 6
gets(buffer);  // Vulnerability 7
gets(buffer);  // Vulnerability 8
gets(buffer);  // Vulnerability 9
gets(buffer);  // Vulnerability 10
gets(buffer);  // Vulnerability 11
gets(buffer);  // Vulnerability 12
gets(buffer);  // Vulnerability 13
gets(buffer);  // Vulnerability 14
gets(buffer);  // Vulnerability 15
gets(buffer);  // Vulnerability 16
gets(buffer);  // Vulnerability 17
gets(buffer);  // Vulnerability 18
gets(buffer);  // Vulnerability 19
gets(buffer);  // Vulnerability 20