// C++ insecure code sample
system(input);  // Vulnerability 1
system(input);  // Vulnerability 2
system(input);  // Vulnerability 3
system(input);  // Vulnerability 4
system(input);  // Vulnerability 5
system(input);  // Vulnerability 6
system(input);  // Vulnerability 7
system(input);  // Vulnerability 8
system(input);  // Vulnerability 9
system(input);  // Vulnerability 10
system(input);  // Vulnerability 11
system(input);  // Vulnerability 12
system(input);  // Vulnerability 13
system(input);  // Vulnerability 14
system(input);  // Vulnerability 15
system(input);  // Vulnerability 16
system(input);  // Vulnerability 17
system(input);  // Vulnerability 18
system(input);  // Vulnerability 19
system(input);  // Vulnerability 20