// C# insecure code sample
Process.Start(userInput);  // Vulnerability 1
Process.Start(userInput);  // Vulnerability 2
Process.Start(userInput);  // Vulnerability 3
Process.Start(userInput);  // Vulnerability 4
Process.Start(userInput);  // Vulnerability 5
Process.Start(userInput);  // Vulnerability 6
Process.Start(userInput);  // Vulnerability 7
Process.Start(userInput);  // Vulnerability 8
Process.Start(userInput);  // Vulnerability 9
Process.Start(userInput);  // Vulnerability 10
Process.Start(userInput);  // Vulnerability 11
Process.Start(userInput);  // Vulnerability 12
Process.Start(userInput);  // Vulnerability 13
Process.Start(userInput);  // Vulnerability 14
Process.Start(userInput);  // Vulnerability 15
Process.Start(userInput);  // Vulnerability 16
Process.Start(userInput);  // Vulnerability 17
Process.Start(userInput);  // Vulnerability 18
Process.Start(userInput);  // Vulnerability 19
Process.Start(userInput);  // Vulnerability 20