// Go insecure code sample
os/exec.Command(input)  // Vulnerability 1
os/exec.Command(input)  // Vulnerability 2
os/exec.Command(input)  // Vulnerability 3
os/exec.Command(input)  // Vulnerability 4
os/exec.Command(input)  // Vulnerability 5
os/exec.Command(input)  // Vulnerability 6
os/exec.Command(input)  // Vulnerability 7
os/exec.Command(input)  // Vulnerability 8
os/exec.Command(input)  // Vulnerability 9
os/exec.Command(input)  // Vulnerability 10
os/exec.Command(input)  // Vulnerability 11
os/exec.Command(input)  // Vulnerability 12
os/exec.Command(input)  // Vulnerability 13
os/exec.Command(input)  // Vulnerability 14
os/exec.Command(input)  // Vulnerability 15
os/exec.Command(input)  // Vulnerability 16
os/exec.Command(input)  // Vulnerability 17
os/exec.Command(input)  // Vulnerability 18
os/exec.Command(input)  // Vulnerability 19
os/exec.Command(input)  // Vulnerability 20