// Java insecure code sample
Runtime.getRuntime().exec(userInput); // Vulnerability 1
Runtime.getRuntime().exec(userInput); // Vulnerability 2
Runtime.getRuntime().exec(userInput); // Vulnerability 3
Runtime.getRuntime().exec(userInput); // Vulnerability 4
Runtime.getRuntime().exec(userInput); // Vulnerability 5
Runtime.getRuntime().exec(userInput); // Vulnerability 6
Runtime.getRuntime().exec(userInput); // Vulnerability 7
Runtime.getRuntime().exec(userInput); // Vulnerability 8
Runtime.getRuntime().exec(userInput); // Vulnerability 9
Runtime.getRuntime().exec(userInput); // Vulnerability 10
Runtime.getRuntime().exec(userInput); // Vulnerability 11
Runtime.getRuntime().exec(userInput); // Vulnerability 12
Runtime.getRuntime().exec(userInput); // Vulnerability 13
Runtime.getRuntime().exec(userInput); // Vulnerability 14
Runtime.getRuntime().exec(userInput); // Vulnerability 15
Runtime.getRuntime().exec(userInput); // Vulnerability 16
Runtime.getRuntime().exec(userInput); // Vulnerability 17
Runtime.getRuntime().exec(userInput); // Vulnerability 18
Runtime.getRuntime().exec(userInput); // Vulnerability 19
Runtime.getRuntime().exec(userInput); // Vulnerability 20