// JS insecure code sample
eval(userInput);  // Vulnerability 1
eval(userInput);  // Vulnerability 2
eval(userInput);  // Vulnerability 3
eval(userInput);  // Vulnerability 4
eval(userInput);  // Vulnerability 5
eval(userInput);  // Vulnerability 6
eval(userInput);  // Vulnerability 7
eval(userInput);  // Vulnerability 8
eval(userInput);  // Vulnerability 9
eval(userInput);  // Vulnerability 10
eval(userInput);  // Vulnerability 11
eval(userInput);  // Vulnerability 12
eval(userInput);  // Vulnerability 13
eval(userInput);  // Vulnerability 14
eval(userInput);  // Vulnerability 15
eval(userInput);  // Vulnerability 16
eval(userInput);  // Vulnerability 17
eval(userInput);  // Vulnerability 18
eval(userInput);  // Vulnerability 19
eval(userInput);  // Vulnerability 20