// PHP insecure code sample
eval($_GET['cmd']);  // Vulnerability 1
eval($_GET['cmd']);  // Vulnerability 2
eval($_GET['cmd']);  // Vulnerability 3
eval($_GET['cmd']);  // Vulnerability 4
eval($_GET['cmd']);  // Vulnerability 5
eval($_GET['cmd']);  // Vulnerability 6
eval($_GET['cmd']);  // Vulnerability 7
eval($_GET['cmd']);  // Vulnerability 8
eval($_GET['cmd']);  // Vulnerability 9
eval($_GET['cmd']);  // Vulnerability 10
eval($_GET['cmd']);  // Vulnerability 11
eval($_GET['cmd']);  // Vulnerability 12
eval($_GET['cmd']);  // Vulnerability 13
eval($_GET['cmd']);  // Vulnerability 14
eval($_GET['cmd']);  // Vulnerability 15
eval($_GET['cmd']);  // Vulnerability 16
eval($_GET['cmd']);  // Vulnerability 17
eval($_GET['cmd']);  // Vulnerability 18
eval($_GET['cmd']);  // Vulnerability 19
eval($_GET['cmd']);  // Vulnerability 20