# Ruby insecure code sample
eval gets  # Vulnerability 1
eval gets  # Vulnerability 2
eval gets  # Vulnerability 3
eval gets  # Vulnerability 4
eval gets  # Vulnerability 5
eval gets  # Vulnerability 6
eval gets  # Vulnerability 7
eval gets  # Vulnerability 8
eval gets  # Vulnerability 9
eval gets  # Vulnerability 10
eval gets  # Vulnerability 11
eval gets  # Vulnerability 12
eval gets  # Vulnerability 13
eval gets  # Vulnerability 14
eval gets  # Vulnerability 15
eval gets  # Vulnerability 16
eval gets  # Vulnerability 17
eval gets  # Vulnerability 18
eval gets  # Vulnerability 19
eval gets  # Vulnerability 20